apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-stress-example
  namespace: chaos-mesh
spec:
  mode: one
  selector:
    namespaces:
      - stress-app  
    labelSelectors:
      app: postgres
  stressors:
    memory:
      workers: 4
      size: '256MB'