kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: chaos-mesh
  name: account-chaos-mesh-manager-oivxb

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: chaos-mesh
  name: role-chaos-mesh-manager-oivxb
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["chaos-mesh.org"]
  resources: [ "*" ]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-chaos-mesh-manager-oivxb
  namespace: chaos-mesh
subjects:
- kind: ServiceAccount
  name: account-chaos-mesh-manager-oivxb
  namespace: chaos-mesh
roleRef:
  kind: Role
  name: role-chaos-mesh-manager-oivxb
  apiGroup: rbac.authorization.k8s.io

---
  # ClusterRole: permissões amplas para todos os recursos Chaos Mesh
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-mesh-manager
rules:
- apiGroups: ["chaos-mesh.org"]
  resources: ["*"]                  # Ou especifique: ["jvmchaos"] para apenas esse recurso
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
# ClusterRoleBinding: liga o ClusterRole ao ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-mesh-manager-binding
subjects:
- kind: ServiceAccount
  name: account-chaos-mesh-manager-oivxb
  namespace: chaos-mesh
roleRef:
  kind: ClusterRole
  name: chaos-mesh-manager
  apiGroup: rbac.authorization.k8s.io