apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: nginx-pod-kill
  namespace: chaos-mesh
spec:
  action: pod-kill
  mode: fixed-percent
  value: '50'
  selector:
    namespaces:
      - chaos-mesh
    labelSelectors:
      app: nginx