apiVersion: v1
kind: Namespace
metadata:
  name: memory-stress-test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-stress-app
  namespace: memory-stress-test
  labels:
    app: memory-stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-stress
  template:
    metadata:
      labels:
        app: memory-stress
    spec:
      containers:
      - name: memory-stress
        image: memory-stress:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MEMORY_TARGET_MB
          value: "500"
        - name: NODE_SIZE_KB
          value: "1"
        - name: DURATION_SECONDS
          value: "3600"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - pgrep
            - python
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: memory-stress-service
  namespace: memory-stress-test
spec:
  selector:
    app: memory-stress
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: memory-stress-hpa
  namespace: memory-stress-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: memory-stress-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70