apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-stress-test
  labels:
    app: memory-stress-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-stress-test
  template:
    metadata:
      labels:
        app: memory-stress-test
    spec:
      containers:
      - name: stress-app
        image: memory-stress-test:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: memory-stress-service
  labels:
    app: memory-stress-test
spec:
  type: NodePort
  selector:
    app: memory-stress-test
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080