apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stress-test
  namespace: stress-app
  labels:
    app: cpu-stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-stress
  template:
    metadata:
      labels:
        app: cpu-stress
    spec:
      containers:
      - name: cpu-stress
        image: cpu-stress:latest
        imagePullPolicy: Never  # Para imagens locais no microk8s
        command: ["python3", "stress_cpu.py"]
        args: ["-d", "300", "-i", "80"]  # 5 minutos, 80% intensidade
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "2000m"  # 2 cores máximo
            memory: "128Mi"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
      restartPolicy: Always