apiVersion: v1
kind: Service
metadata:
  name: cpu-stress-service
  labels:
    app: cpu-stress
spec:
  selector:
    app: cpu-stress
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP