apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: stress-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stress-test
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: stress
      maxAllowed:
        cpu: "2"
        memory: "2Gi"