apiVersion: v1
kind: Service
metadata:
  namespace: stress-app
  name: postgres-service
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30432  # Porta que será exposta no node
    protocol: TCP
  type: NodePort     # Mudança aqui