apiVersion: v1
kind: Namespace
metadata:
  name: tcc-degradacao
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-degradacao
  namespace: tcc-degradacao
  labels:
    app: degradacao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: degradacao
  template:
    metadata:
      labels:
        app: degradacao
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: app
        image: degradacao-test:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: app-degradacao-service
  namespace: tcc-degradacao
spec:
  selector:
    app: degradacao
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30060  # Opcional: porta entre 30000-32767
  type: NodePort