apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    app: cadvisor
    version: v2.1
spec:
  type: NodePort
  ports:
  - port: 8070
    targetPort: 8070
    nodePort: 31194
    name: cadvisor
  selector:
    app: cadvisor