apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cadvisor
  namespace: observability
  labels:
    app: cadvisor
spec:
  selector:
    matchLabels:
      app: cadvisor
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - observability