apiVersion: v1
kind: Pod
metadata:
  name: cadvisor-test
  namespace: default
spec:
  hostNetwork: true
  hostPID: true
  automountServiceAccountToken: false
  containers:
  - name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    args:
      - --housekeeping_interval=30s
      - --disable_metrics=percpu,sched,tcp,udp
    securityContext:
      privileged: true
    volumeMounts:
    - name: rootfs
      mountPath: /rootfs
      readOnly: true
    - name: var-run
      mountPath: /var/run
      readOnly: true
    - name: sys
      mountPath: /sys
      readOnly: true
  volumes:
  - name: rootfs
    hostPath:
      path: /
  - name: var-run
    hostPath:
      path: /var/run
  - name: sys
    hostPath:
      path: /sys
  restartPolicy: Never
