apiVersion: v1
kind: Service
metadata:
  name: prometheus-alertmanager
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9093
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-alertmanager-headless
  namespace: monitoring
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 9093
      targetPort: http
      protocol: TCP
    - name: cluster
      port: 9094
      targetPort: cluster
      protocol: TCP
  selector:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: prometheus