apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: monitoring
  name: alertmanager-pv-0
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /opt/prometheus/alertmanager
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - seu-node-name  # Substitua pelo nome do seu nรณ