apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: monitoring
  name: prometheus-alertmanager
spec:
  serviceName: prometheus-alertmanager-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/instance: prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alertmanager
        app.kubernetes.io/instance: prometheus
    spec:
      serviceAccountName: prometheus-alertmanager
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        fsGroup: 65534
      containers:
        - name: alertmanager
          image: quay.io/prometheus/alertmanager:v0.28.1
          args:
            - '--storage.path=/alertmanager'
            - '--config.file=/etc/alertmanager/alertmanager.yml'
            - '--cluster.listen-address=0.0.0.0:9094'
            - '--web.listen-address=0.0.0.0:9093'
            - '--web.external-url=http://localhost:9093/'
            - '--log.level=info'
          ports:
            - name: http
              containerPort: 9093
              protocol: TCP
            - name: cluster
              containerPort: 9094
              protocol: TCP
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          # ✅ ADICIONAR RESOURCES
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
            - name: storage
              mountPath: /alertmanager
          # ✅ CORRIGIR HEALTH CHECKS
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: config
          configMap:
            name: prometheus-alertmanager
            defaultMode: 420
  # ✅ ADICIONAR VOLUME CLAIM TEMPLATE
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-storage  # Use sua StorageClass
        resources:
          requests:
            storage: 2Gi